//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassActivity2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lgemployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lgemployee()
        {
            this.lginvoices = new HashSet<lginvoice>();
        }
    
        public decimal emp_num { get; set; }
        public string emp_fname { get; set; }
        public string emp_lname { get; set; }
        public string emp_email { get; set; }
        public string emp_phone { get; set; }
        public System.DateTime emp_hireDATETIME { get; set; }
        public string emp_title { get; set; }
        public Nullable<decimal> emp_comm { get; set; }
        public Nullable<decimal> dept_num { get; set; }
    
        public virtual lgdepartment lgdepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lginvoice> lginvoices { get; set; }
        public virtual lgsalary_history lgsalary_history { get; set; }
    }
}
